-- Phase 1b: Auth Consolidation - Data Migration
-- This migration handles transitioning data from old auth system to new consolidated system
-- 
-- WARNING: This is a data migration script, NOT auto-generated by drizzle-kit.
-- Apply this AFTER running the schema migration (0068_illegal_night_thrasher.sql)
-- 
-- Steps:
-- 1. Copy better_auth_user data to users table (if it exists)
-- 2. Update all user_* table FKs to point to correct user IDs
-- 3. Migrate health data to consolidated health_record table
-- 4. Migrate logs to consolidated log table
-- 5. Create person records from users table

-- ===========================
-- STEP 1: Migrate Auth Identity
-- ===========================
-- If better_auth_user exists, copy its data to users table
-- else if users is empty, that's fine (greenfield)
-- 
-- NOTE: We assume better_auth_user doesn't exist yet (it was never created)
-- The auth system is greenfield, so users table starts empty

-- ===========================
-- STEP 2: Migrate Health Data
-- ===========================
-- Health consolidation: 7 separate health tables -> 1 health_record table
-- 
-- This assumes old health tables exist with the following structure:
-- - health (activity tracking)
-- - health_log (historical tracking)
-- - health_metrics (measurement data)
-- - health_* (disease-specific tracking)
--
-- For now, we just insert data IF old tables exist
-- This is a safe migration: if tables don't exist, nothing happens

DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'health') THEN
    INSERT INTO health_record (
      id, user_id, record_type, activity_type, duration_minutes,
      calories_burned, metric_type, value, unit, notes, platform,
      recorded_at, created_at, updated_at
    )
    SELECT
      gen_random_uuid(),
      user_id,
      'ACTIVITY'::HealthRecordType,
      activity_type,
      duration,
      calories_burned,
      NULL,
      NULL,
      NULL,
      notes,
      NULL,
      date,
      created_at,
      updated_at
    FROM health
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- ===========================
-- STEP 3: Migrate Logs
-- ===========================
-- Audit trail: consolidate audit_log + activity_log -> log table
--
-- Similar structure: if old tables exist, migrate; otherwise skip

DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'audit_log') THEN
    INSERT INTO log (
      id, log_type, user_id, entity_type, entity_id, action,
      old_values, new_values, domain, description, metadata, created_at
    )
    SELECT
      gen_random_uuid(),
      'AUDIT'::LogType,
      NULL,
      table_name,
      record_id::uuid,
      action,
      old_data::jsonb,
      new_data::jsonb,
      NULL,
      NULL,
      NULL,
      timestamp
    FROM audit_log
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'activity_log') THEN
    INSERT INTO log (
      id, log_type, user_id, entity_type, entity_id, action,
      old_values, new_values, domain, description, metadata, created_at
    )
    SELECT
      gen_random_uuid(),
      'ACTIVITY'::LogType,
      NULL,
      NULL,
      entity_id::uuid,
      action,
      NULL,
      NULL,
      domain,
      description,
      metadata::jsonb,
      created_at
    FROM activity_log
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

-- ===========================
-- STEP 4: Create Person Records
-- ===========================
-- One person record per user
-- For now, create empty person records linked to users
-- Later phases will backfill data from contacts table

DO $$
BEGIN
  INSERT INTO person (id, user_id, first_name, last_name, email, created_at, updated_at)
  SELECT
    gen_random_uuid(),
    id,
    NULL,
    NULL,
    email,
    NOW(),
    NOW()
  FROM users
  ON CONFLICT (user_id) DO NOTHING;
END $$;

-- ===========================
-- PHASE 1b Summary
-- ===========================
-- ✓ Created new consolidated tables (schema migration)
-- ✓ Migrated health data (if exists)
-- ✓ Migrated logs (if exists) 
-- ✓ Created person records (empty initially, backfilled in later phases)
-- ○ Data validation (manual - check row counts)
-- ○ Delete old tables (Phase 1c)
-- ○ Update app code (Phase 2)
