// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/auth/google": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/chat/:chatId": {
    params: {
      "chatId": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/settings/archived-chats": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/auth/google" | "/auth" | "/logout" | "/chat/:chatId" | "/settings" | "/settings/archived-chats" | "/*";
  };
  "routes/api/auth/google.ts": {
    id: "routes/api/auth/google";
    page: "/api/auth/google";
  };
  "routes/auth/index.tsx": {
    id: "routes/auth/index";
    page: "/auth";
  };
  "routes/auth/logout.tsx": {
    id: "routes/auth/logout";
    page: "/logout";
  };
  "routes/_authenticated.tsx": {
    id: "routes/_authenticated";
    page: "/" | "/chat/:chatId" | "/settings" | "/settings/archived-chats";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/chat/:chatId" | "/settings" | "/settings/archived-chats";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/chat/chat.$chatId.tsx": {
    id: "routes/chat/chat.$chatId";
    page: "/chat/:chatId";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/settings.archived-chats.tsx": {
    id: "routes/settings.archived-chats";
    page: "/settings/archived-chats";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api/auth/google": typeof import("./app/routes/api/auth/google.ts");
  "routes/auth/index": typeof import("./app/routes/auth/index.tsx");
  "routes/auth/logout": typeof import("./app/routes/auth/logout.tsx");
  "routes/_authenticated": typeof import("./app/routes/_authenticated.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/chat/chat.$chatId": typeof import("./app/routes/chat/chat.$chatId.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/settings.archived-chats": typeof import("./app/routes/settings.archived-chats.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};