app = "hominem-workers"
primary_region = "sjc"

[build]
  dockerfile = "../services/workers/Dockerfile"

[env]
  NODE_ENV = "production"
  APP_BASE_URL = "https://app.ponti.io"
  PLAID_ENV = "production"
  OTEL_SERVICE_NAME = "hominem-workers"
  OTEL_DEPLOYMENT_ENVIRONMENT = "production"
  OTEL_EXPORTER_OTLP_PROTOCOL = "http/protobuf"
  OTEL_TRACES_SAMPLER_ARG = "1.0"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
