[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "cd apps/hominem-api && npm start"
healthcheckPath = "/status"
healthcheckTimeout = 100
restartPolicyType = "never"
