[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node apps/hominem-api/build/src/index"
healthcheckPath = "/status"
healthcheckTimeout = 100
restartPolicyType = "never"
