[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "bun run apps/hominem-api/src/index.ts"
healthcheckPath = "/status"
healthcheckTimeout = 100
restartPolicyType = "never"
