[build]
builder = "nixpacks"
buildCommand = "bun run build"

[deploy]
startCommand = "bun run apps/api/build/src/index"
healthcheckPath = "/status"
healthcheckTimeout = 100
restartPolicyType = "never"
