-- +goose Up
-- +goose StatementBegin
-- `sequence` was app-computed (SELECT MAX + increment under a row lock),
-- which forced every append to replay the generation's full event history
-- just to find the next value. Retrofitting it to a DB identity column lets
-- Postgres assign it, so appendEvent no longer needs that replay. The
-- sequence becomes a global monotonic counter (shared across all
-- generations) instead of restarting at 1 per generation — every consumer
-- only compares/orders `sequence` within one generationId scope
-- (UNIQUE(generation_id, sequence), the afterSequence cursor in listEvents),
-- so global uniqueness+monotonicity is a strictly sufficient replacement.
ALTER TABLE app.chat_generation_events
  ALTER COLUMN sequence ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
  pg_get_serial_sequence('app.chat_generation_events', 'sequence'),
  COALESCE((SELECT MAX(sequence) FROM app.chat_generation_events), 0) + 1,
  false
);

-- Moves NOTIFY from an explicit app-level `select pg_notify(...)` statement
-- (its own round trip) to a trigger fired by the insert itself. Same
-- guarantee as before: Postgres only delivers NOTIFY on commit and discards
-- it on rollback, so live delivery stays atomic with the durable write.
-- Payload is kept to the same small pointer (generationId + sequence, not
-- the full event) NOTIFY payloads are capped at 8000 bytes and a full event
-- (long assistant text, large tool-call arguments) can exceed that.
CREATE OR REPLACE FUNCTION app.notify_chat_generation_event()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM pg_notify(
    'chat_generation_events',
    json_build_object('generationId', NEW.generation_id, 'sequence', NEW.sequence)::text
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER chat_generation_events_notify
  AFTER INSERT ON app.chat_generation_events
  FOR EACH ROW EXECUTE FUNCTION app.notify_chat_generation_event();
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS chat_generation_events_notify ON app.chat_generation_events;
DROP FUNCTION IF EXISTS app.notify_chat_generation_event();
ALTER TABLE app.chat_generation_events
  ALTER COLUMN sequence DROP IDENTITY IF EXISTS;
-- +goose StatementEnd
