/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: ColumnType<string, Date | string, Date | string> | null;
  accountId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: ColumnType<string, Date | string, Date | string> | null;
  scope: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppAiUsageEvents {
  cachedInputTokens: number | null;
  costUsd: Numeric | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  durationMs: number | null;
  errorCode: string | null;
  errorStatus: number | null;
  feature: string;
  id: Generated<string>;
  inputTokens: number;
  metadata: Json | null;
  model: string | null;
  operation: string;
  outputTokens: number;
  ownerUserid: string;
  provider: string;
  reasoningTokens: number | null;
  requestId: string | null;
  status: Generated<string>;
  totalTokens: number;
  usageAvailable: Generated<boolean>;
}

export interface AppApplicationNotes {
  applicationId: string;
  content: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  isPrivate: Generated<boolean>;
  title: string | null;
  type: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCareerEvents {
  achievements: Generated<Json>;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  details: Generated<Json>;
  eventDate: ColumnType<string, Date | string, Date | string>;
  eventType: string;
  id: Generated<string>;
  ownerUserid: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  workExperienceId: string | null;
}

export interface AppChatMessages {
  authorUserid: string | null;
  chatId: string;
  content: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  files: Json | null;
  id: Generated<string>;
  parentMessageId: string | null;
  reasoning: string | null;
  referencedNoteIds: Json | null;
  role: string;
  toolCalls: Json | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppChats {
  archivedAt: ColumnType<string, Date | string, Date | string> | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  lastMessageAt: Generated<ColumnType<string, Date | string, Date | string>>;
  noteId: string | null;
  ownerUserid: string;
  primarySpaceId: string | null;
  source: string | null;
  title: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCompanies {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  id: Generated<string>;
  industry: string | null;
  location: string | null;
  name: string;
  ownerUserid: string;
  size: number | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  website: string | null;
}

export interface AppFiles {
  content: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  metadata: Json | null;
  mimetype: string;
  originalName: string;
  ownerUserid: string;
  size: number;
  storageKey: string;
  textContent: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  url: string;
}

export interface AppFinanceAccounts {
  accountSubtype: string | null;
  accountType: string;
  availableBalance: Numeric | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  csvImportKey: string | null;
  currencyCode: Generated<string>;
  currentBalance: Numeric | null;
  id: Generated<string>;
  institutionId: string | null;
  isActive: Generated<boolean>;
  mask: string | null;
  metadata: Generated<Json>;
  name: string;
  plaidAccountId: string | null;
  plaidItemId: string | null;
  provider: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppFinanceInstitutions {
  countryCode: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  logoUrl: string | null;
  name: string;
  provider: string | null;
  providerInstitutionId: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  websiteUrl: string | null;
}

export interface AppFinanceTransactions {
  accountId: string;
  amount: Numeric;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  excluded: Generated<boolean>;
  externalId: string | null;
  id: Generated<string>;
  merchantName: string | null;
  notes: string | null;
  occurredAt: ColumnType<string, Date | string, Date | string> | null;
  pending: Generated<boolean>;
  postedOn: ColumnType<string, Date | string, Date | string>;
  providerPayload: Generated<Json>;
  source: string | null;
  transactionType: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppJobApplications {
  applicationDate: ColumnType<string, Date | string, Date | string> | null;
  bonusFinal: number | null;
  bonusOffered: number | null;
  companyId: string;
  companyNotes: string | null;
  coverLetter: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  decisionDate: ColumnType<string, Date | string, Date | string> | null;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  equityFinal: string | null;
  equityOffered: string | null;
  firstInterviewDate: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  interviewDates: Generated<Json>;
  jobId: string | null;
  jobPosting: string | null;
  jobPostingUrl: string | null;
  jobPostingWordCount: number | null;
  link: string | null;
  location: string | null;
  negotiationNotes: string | null;
  offerDate: ColumnType<string, Date | string, Date | string> | null;
  ownerUserid: string;
  phoneScreen: string | null;
  position: string;
  recruiterEmail: string | null;
  recruiterLinkedin: string | null;
  recruiterName: string | null;
  reference: Generated<boolean>;
  rejectionReason: string | null;
  requirements: Generated<Json>;
  responseDate: ColumnType<string, Date | string, Date | string> | null;
  resume: string | null;
  salaryAccepted: string | null;
  salaryExpected: number | null;
  salaryFinal: number | null;
  salaryNegotiated: number | null;
  salaryOffered: number | null;
  salaryQuoted: string | null;
  salaryRequested: number | null;
  skills: Generated<Json>;
  source: string | null;
  stages: Generated<Json>;
  startDate: ColumnType<string, Date | string, Date | string>;
  status: string;
  timeToDecision: number | null;
  timeToFirstInterview: number | null;
  timeToOffer: number | null;
  timeToResponse: number | null;
  totalCompFinal: number | null;
  totalCompOffered: number | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  withdrawalReason: string | null;
}

export interface AppJobApplicationStatusHistory {
  applicationId: string;
  changedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  newStatus: string;
  previousStatus: string | null;
}

export interface AppNoteFiles {
  attachedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  fileId: string;
  noteId: string;
}

export interface AppNotes {
  archivedAt: ColumnType<string, Date | string, Date | string> | null;
  content: Generated<string>;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  currentVersionId: string | null;
  excerpt: string | null;
  id: Generated<string>;
  isLocked: Generated<boolean>;
  ownerUserid: string;
  parentNoteId: string | null;
  source: string | null;
  title: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppPlaidItems {
  accessToken: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  cursor: string | null;
  errorCode: string | null;
  errorMessage: string | null;
  id: Generated<string>;
  institutionId: string | null;
  lastSyncedAt: ColumnType<string, Date | string, Date | string> | null;
  provider: Generated<string>;
  providerItemId: string;
  status: Generated<string>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppPortfolios {
  availabilityStatus: Generated<boolean>;
  bio: string;
  copyright: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  currentLocation: string;
  email: string;
  id: Generated<string>;
  initials: string | null;
  isActive: Generated<boolean>;
  isPublic: Generated<boolean>;
  jobTitle: string;
  name: string;
  openToRemote: Generated<boolean>;
  ownerUserid: string;
  phone: string | null;
  profileImageUrl: string | null;
  slug: string;
  tagline: string;
  title: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppProjects {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  githubUrl: string | null;
  id: Generated<string>;
  imageUrl: string | null;
  isFeatured: Generated<boolean>;
  isVisible: Generated<boolean>;
  liveUrl: string | null;
  portfolioId: string;
  shortDescription: string | null;
  sortOrder: Generated<number>;
  startDate: ColumnType<string, Date | string, Date | string> | null;
  status: Generated<string>;
  technologies: Generated<Json>;
  title: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  videoUrl: string | null;
  workExperienceId: string | null;
}

export interface AppSkills {
  aiDerived: Generated<boolean>;
  category: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  icon: string | null;
  id: Generated<string>;
  isVisible: Generated<boolean>;
  level: number;
  name: string;
  portfolioId: string;
  proof: string | null;
  sortOrder: Generated<number>;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  yearsOfExperience: number | null;
}

export interface AppSkillSources {
  careerEventId: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  projectId: string | null;
  skillId: string;
  workExperienceId: string | null;
}

export interface AppTagAssignments {
  assignedByUserid: string | null;
  assignmentPeriod: Generated<string | null>;
  assignmentSource: Generated<string>;
  confidence: Numeric | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  entityId: string;
  entityTable: string;
  id: Generated<string>;
  removedAt: ColumnType<string, Date | string, Date | string> | null;
  tagId: string;
}

export interface AppTags {
  archivedAt: ColumnType<string, Date | string, Date | string> | null;
  color: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  createdByUserid: string | null;
  description: string | null;
  icon: string | null;
  id: Generated<string>;
  name: string;
  ownerUserid: string;
  path: string;
  slug: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppTaskParticipants {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  displayName: string;
  email: string | null;
  id: Generated<string>;
  personId: string | null;
  taskId: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppTasks {
  completedAt: ColumnType<string, Date | string, Date | string> | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  dueAt: ColumnType<string, Date | string, Date | string> | null;
  durationMinutes: number | null;
  id: Generated<string>;
  location: string | null;
  ownerUserid: string;
  parentTaskId: string | null;
  primarySpaceId: string | null;
  priority: Generated<string>;
  scheduledEndAt: ColumnType<string, Date | string, Date | string> | null;
  scheduledStartAt: ColumnType<string, Date | string, Date | string> | null;
  schedulingWindowEndAt: ColumnType<string, Date | string, Date | string> | null;
  schedulingWindowStartAt: ColumnType<string, Date | string, Date | string> | null;
  status: Generated<string>;
  timeZone: string | null;
  title: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppTestimonials {
  avatarUrl: string | null;
  company: string | null;
  content: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  isVerified: Generated<boolean>;
  isVisible: Generated<boolean>;
  linkedinUrl: string | null;
  name: string;
  portfolioId: string;
  rating: number | null;
  sortOrder: Generated<number>;
  title: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppUserSocialLinks {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  github: string | null;
  linkedin: string | null;
  twitter: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
  website: string | null;
}

export interface AppVectorDocuments {
  content: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  embedding: string;
  entityId: string;
  entityType: string;
  id: Generated<string>;
  metadata: Json | null;
  ownerUserid: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppWorkExperiences {
  action: string | null;
  annualBonus: number | null;
  baseSalary: number | null;
  benefits: Json | null;
  bonusHistory: Generated<Json>;
  company: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  currency: Generated<string>;
  department: string | null;
  description: string;
  directReports: Generated<number>;
  employmentType: Generated<string>;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  exitNotes: string | null;
  gradient: string | null;
  id: Generated<string>;
  image: string | null;
  isVisible: Generated<boolean>;
  metadata: Json | null;
  metrics: string | null;
  performanceRatings: Generated<Json>;
  portfolioId: string;
  reasonForLeaving: string | null;
  reportsTo: string | null;
  role: string;
  salaryAdjustments: Generated<Json>;
  salaryRange: Json | null;
  seniorityLevel: string | null;
  signingBonus: number | null;
  sortOrder: Generated<number>;
  startDate: ColumnType<string, Date | string, Date | string> | null;
  tags: Generated<Json>;
  teamSize: number | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  workArrangement: Generated<string>;
}

export interface DeviceCode {
  clientId: string | null;
  deviceCode: string;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  lastPolledAt: ColumnType<string, Date | string, Date | string> | null;
  pollingInterval: number | null;
  scope: string | null;
  status: string;
  userCode: string;
  userId: string | null;
}

export interface DrizzleDrizzleMigrations {
  createdAt: Int8 | null;
  hash: string;
  id: Generated<number>;
}

export interface GooseDbVersion {
  id: Generated<number>;
  isApplied: boolean;
  tstamp: Generated<ColumnType<string, Date | string, Date | string>>;
  versionId: Int8;
}

export interface Jwks {
  createdAt: ColumnType<string, Date | string, Date | string>;
  expiresAt: ColumnType<string, Date | string, Date | string> | null;
  id: string;
  privateKey: string;
  publicKey: string;
}

export interface LabsArticles {
  description: string | null;
  feedId: number;
  fetchedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<number>;
  imageUrl: string | null;
  publishedAt: ColumnType<string, Date | string, Date | string> | null;
  rejectionCount: Generated<number>;
  rejectionReason: string | null;
  status: Generated<string>;
  title: string;
  url: string;
}

export interface LabsDailyPuzzles {
  answer: string;
  answerType: string;
  articleId: number;
  clue: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  dateUtc: ColumnType<string, Date | string, Date | string>;
  detail: string;
  gameId: number;
  id: Generated<number>;
  normalizedAnswer: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface LabsDrizzleMigrations {
  createdAt: Int8 | null;
  hash: string;
  id: Generated<number>;
}

export interface LabsFeedGames {
  feedId: number;
  gameId: number;
}

export interface LabsFeeds {
  active: Generated<boolean>;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<number>;
  kind: Generated<string>;
  label: string;
  url: string;
}

export interface LabsGames {
  active: Generated<boolean>;
  answerLength: Generated<number>;
  articleExpiryDays: Generated<number>;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<number>;
  name: string;
  repeatWindowDays: Generated<number>;
  slug: string;
  systemPromptPath: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface LabsRealiteaAttempts {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  dateUtc: ColumnType<string, Date | string, Date | string>;
  gameId: number;
  guessedAt: Generated<Json>;
  guesses: Generated<Json>;
  hominemUserId: string;
  id: Generated<number>;
  status: Generated<string>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface LabsSearchDocuments {
  body: string;
  category: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  embedding: string;
  featured: Generated<boolean>;
  id: Generated<number>;
  kind: string;
  location: string;
  popularity: Generated<number>;
  publishedAt: ColumnType<string, Date | string, Date | string>;
  searchText: string;
  searchVector: Generated<string>;
  sourceUrl: string;
  subtitle: string;
  summary: string;
  tags: Json;
  title: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  year: number;
}

export interface OauthAccessToken {
  accessToken: string;
  accessTokenExpiresAt: ColumnType<string, Date | string, Date | string>;
  clientId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  refreshToken: string;
  refreshTokenExpiresAt: ColumnType<string, Date | string, Date | string>;
  scopes: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string | null;
}

export interface OauthApplication {
  clientId: string;
  clientSecret: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  disabled: Generated<boolean>;
  icon: string | null;
  id: string;
  metadata: string | null;
  name: string;
  redirectUrls: string;
  type: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string | null;
}

export interface OauthConsent {
  clientId: string;
  consentGiven: Generated<boolean>;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  scopes: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface Passkey {
  aaguid: string | null;
  backedUp: Generated<boolean>;
  counter: Generated<number>;
  createdAt: ColumnType<string, Date | string, Date | string> | null;
  credentialID: string;
  deviceType: string;
  id: string;
  name: string | null;
  publicKey: string;
  transports: string | null;
  userId: string;
}

export interface Session {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface Verification {
  createdAt: ColumnType<string, Date | string, Date | string> | null;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  identifier: string;
  updatedAt: ColumnType<string, Date | string, Date | string> | null;
  value: string;
}

export interface DB {
  account: Account;
  'app.aiUsageEvents': AppAiUsageEvents;
  'app.applicationNotes': AppApplicationNotes;
  'app.careerEvents': AppCareerEvents;
  'app.chatMessages': AppChatMessages;
  'app.chats': AppChats;
  'app.companies': AppCompanies;
  'app.files': AppFiles;
  'app.financeAccounts': AppFinanceAccounts;
  'app.financeInstitutions': AppFinanceInstitutions;
  'app.financeTransactions': AppFinanceTransactions;
  'app.jobApplications': AppJobApplications;
  'app.jobApplicationStatusHistory': AppJobApplicationStatusHistory;
  'app.noteFiles': AppNoteFiles;
  'app.notes': AppNotes;
  'app.plaidItems': AppPlaidItems;
  'app.portfolios': AppPortfolios;
  'app.projects': AppProjects;
  'app.skills': AppSkills;
  'app.skillSources': AppSkillSources;
  'app.tagAssignments': AppTagAssignments;
  'app.tags': AppTags;
  'app.taskParticipants': AppTaskParticipants;
  'app.tasks': AppTasks;
  'app.testimonials': AppTestimonials;
  'app.userSocialLinks': AppUserSocialLinks;
  'app.vectorDocuments': AppVectorDocuments;
  'app.workExperiences': AppWorkExperiences;
  deviceCode: DeviceCode;
  'drizzle.DrizzleMigrations': DrizzleDrizzleMigrations;
  gooseDbVersion: GooseDbVersion;
  jwks: Jwks;
  'labs.articles': LabsArticles;
  'labs.dailyPuzzles': LabsDailyPuzzles;
  'labs.DrizzleMigrations': LabsDrizzleMigrations;
  'labs.feedGames': LabsFeedGames;
  'labs.feeds': LabsFeeds;
  'labs.games': LabsGames;
  'labs.realiteaAttempts': LabsRealiteaAttempts;
  'labs.searchDocuments': LabsSearchDocuments;
  oauthAccessToken: OauthAccessToken;
  oauthApplication: OauthApplication;
  oauthConsent: OauthConsent;
  passkey: Passkey;
  session: Session;
  user: User;
  verification: Verification;
}
