/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: ColumnType<string, Date | string, Date | string> | null;
  accountId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: ColumnType<string, Date | string, Date | string> | null;
  scope: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppAiUsageEvents {
  cachedInputTokens: number | null;
  costUsd: Numeric | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  durationMs: number | null;
  errorCode: string | null;
  errorStatus: number | null;
  feature: string;
  id: Generated<string>;
  inputTokens: number;
  metadata: Json | null;
  model: string | null;
  operation: string;
  outputTokens: number;
  ownerUserid: string;
  provider: string;
  reasoningTokens: number | null;
  requestId: string | null;
  status: Generated<string>;
  totalTokens: number;
  usageAvailable: Generated<boolean>;
}

export interface AppCareerApplicationFiles {
  applicationId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  fileName: string;
  fileType: string | null;
  fileUrl: string;
  id: Generated<string>;
}

export interface AppCareerApplicationNotes {
  applicationId: string;
  content: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
}

export interface AppCareerApplications {
  appliedAt: ColumnType<string, Date | string, Date | string> | null;
  company: string;
  coverLetterUrl: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  currentStage: string | null;
  id: Generated<string>;
  jobPostingUrl: string | null;
  legacyId: string | null;
  location: string | null;
  notes: string | null;
  ownerUserid: string;
  referredBy: string | null;
  resumeUrl: string | null;
  salaryExpectation: number | null;
  source: string | null;
  status: string | null;
  title: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCareerApplicationStages {
  applicationId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  enteredAt: ColumnType<string, Date | string, Date | string> | null;
  exitedAt: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  notes: string | null;
  stage: string;
}

export interface AppCareerCertifications {
  category: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  expirationDate: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  issueDate: ColumnType<string, Date | string, Date | string> | null;
  issuingOrganization: string;
  isVisible: Generated<boolean>;
  name: string;
  ownerUserid: string;
  positionId: string | null;
  sortOrder: Generated<number>;
  status: Generated<string | null>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCareerEducation {
  activities: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  degree: string | null;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  fieldOfStudy: string | null;
  id: Generated<string>;
  notes: string | null;
  ownerUserid: string;
  school: string;
  startDate: ColumnType<string, Date | string, Date | string> | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppCareerOffers {
  applicationId: string | null;
  baseSalary: number | null;
  bonus: number | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  currency: Generated<string | null>;
  decision: string | null;
  decisionAt: ColumnType<string, Date | string, Date | string> | null;
  equity: string | null;
  id: Generated<string>;
  notes: string | null;
  signingBonus: number | null;
  totalComp: number | null;
}

export interface AppCareerPositions {
  address: string | null;
  company: string;
  contactName: string | null;
  contactPhone: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  currency: Generated<string | null>;
  description: string | null;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  isCurrent: Generated<boolean | null>;
  isTarget: Generated<boolean | null>;
  location: string | null;
  ownerUserid: string;
  projectStatus: string | null;
  recordType: Generated<string>;
  salaryHigh: number | null;
  salaryLow: number | null;
  source: Generated<string | null>;
  startDate: ColumnType<string, Date | string, Date | string> | null;
  title: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  url: string | null;
}

export interface AppCareerProfile {
  availabilityStatus: Generated<boolean>;
  birthDate: ColumnType<string, Date | string, Date | string> | null;
  copyright: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  email: string | null;
  firstName: string | null;
  headline: string | null;
  id: Generated<string>;
  industry: string | null;
  initials: string | null;
  isActive: Generated<boolean>;
  isPublic: Generated<boolean>;
  lastName: string | null;
  linkedinUrl: string | null;
  location: string | null;
  openToRemote: Generated<boolean>;
  ownerUserid: string;
  phone: string | null;
  profileImageUrl: string | null;
  registeredAt: ColumnType<string, Date | string, Date | string> | null;
  slug: string | null;
  summary: string | null;
  tagline: string | null;
  title: string | null;
  twitterHandles: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  websites: string | null;
}

export interface AppCareerProjects {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  endDate: ColumnType<string, Date | string, Date | string> | null;
  githubUrl: string | null;
  id: Generated<string>;
  imageUrl: string | null;
  isFeatured: Generated<boolean>;
  isVisible: Generated<boolean>;
  liveUrl: string | null;
  ownerUserid: string;
  positionId: string | null;
  shortDescription: string | null;
  sortOrder: Generated<number>;
  startDate: ColumnType<string, Date | string, Date | string> | null;
  status: Generated<string | null>;
  technologies: Generated<Json>;
  title: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  videoUrl: string | null;
}

export interface AppCareerSkills {
  aiDerived: Generated<boolean>;
  category: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  id: Generated<string>;
  isVisible: Generated<boolean>;
  level: number | null;
  name: string;
  ownerUserid: string;
  proof: string | null;
  sortOrder: Generated<number>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  yearsOfExperience: number | null;
}

export interface AppCareerSocialLinks {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  github: string | null;
  id: Generated<string>;
  linkedin: string | null;
  ownerUserid: string;
  twitter: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  website: string | null;
}

export interface AppCareerTestimonials {
  avatarUrl: string | null;
  company: string | null;
  content: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  isVerified: Generated<boolean>;
  isVisible: Generated<boolean>;
  linkedinUrl: string | null;
  name: string;
  ownerUserid: string;
  rating: number | null;
  sortOrder: Generated<number>;
  title: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppChatMessages {
  authorUserid: string | null;
  chatId: string;
  content: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  files: Json | null;
  id: Generated<string>;
  parentMessageId: string | null;
  reasoning: string | null;
  referencedNoteIds: Json | null;
  role: string;
  toolCalls: Json | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppChats {
  archivedAt: ColumnType<string, Date | string, Date | string> | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  lastMessageAt: Generated<ColumnType<string, Date | string, Date | string>>;
  noteId: string | null;
  ownerUserid: string;
  primarySpaceId: string | null;
  source: string | null;
  title: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppFiles {
  content: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  metadata: Json | null;
  mimetype: string;
  originalName: string;
  ownerUserid: string;
  size: number;
  storageKey: string;
  textContent: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
  url: string;
}

export interface AppFinanceAccountLabels {
  accountId: string;
  confidence: Generated<number>;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  effectiveFrom: ColumnType<string, Date | string, Date | string> | null;
  effectiveTo: ColumnType<string, Date | string, Date | string> | null;
  id: Generated<string>;
  institution: string | null;
  isGeneric: Generated<boolean>;
  label: string;
  labelKind: string;
  note: string | null;
  resolvesToAccount: Generated<boolean>;
  source: Generated<string>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppFinanceAccounts {
  accountSubtype: string | null;
  accountType: string;
  availableBalance: Numeric | null;
  closedOn: ColumnType<string, Date | string, Date | string> | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  csvImportKey: string | null;
  currencyCode: Generated<string>;
  currentBalance: Numeric | null;
  id: Generated<string>;
  includeInNetWorth: Generated<boolean>;
  institution: string | null;
  institutionId: string | null;
  isActive: Generated<boolean>;
  lifecycleStatus: Generated<string>;
  mask: string | null;
  metadata: Generated<Json>;
  name: string;
  openedOn: ColumnType<string, Date | string, Date | string> | null;
  plaidAccountId: string | null;
  plaidItemId: string | null;
  provider: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppFinanceCategories {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  name: string;
  parentId: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppFinanceInstitutions {
  countryCode: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: Generated<string>;
  logoUrl: string | null;
  name: string;
  provider: string | null;
  providerInstitutionId: string | null;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  websiteUrl: string | null;
}

export interface AppFinanceStatementPeriods {
  accountId: string;
  certificationStatus: Generated<string>;
  closingBalance: Generated<Numeric>;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  currencyCode: Generated<string>;
  evidencePath: string | null;
  id: Generated<string>;
  note: string | null;
  openingBalance: Generated<Numeric>;
  periodEndOn: ColumnType<string, Date | string, Date | string>;
  periodStartOn: ColumnType<string, Date | string, Date | string>;
  source: Generated<string>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppFinanceTaxFilings {
  appName: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  externalFilingId: string;
  filingTypeRaw: string;
  id: Generated<string>;
  jurisdiction: string;
  postmarkAt: ColumnType<string, Date | string, Date | string> | null;
  receivedAt: ColumnType<string, Date | string, Date | string> | null;
  returnType: string;
  taxYear: number;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppFinanceTaxFilingStatusEvents {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  filingId: string;
  filingTypeRaw: string | null;
  id: Generated<string>;
  message: string | null;
  occurredAt: ColumnType<string, Date | string, Date | string>;
  statusCode: number;
  userId: string;
}

export interface AppFinanceTransactions {
  accountId: string;
  accountMask: string | null;
  amount: Numeric;
  categoryAssignmentSource: Generated<string>;
  categoryId: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  currencyCode: Generated<string>;
  description: string | null;
  excluded: Generated<boolean>;
  externalId: string | null;
  id: Generated<string>;
  merchantName: string | null;
  notes: string | null;
  occurredAt: ColumnType<string, Date | string, Date | string> | null;
  pending: Generated<boolean>;
  postedOn: ColumnType<string, Date | string, Date | string>;
  providerPayload: Generated<Json>;
  recurring: Generated<boolean>;
  source: string | null;
  transactionType: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppNoteFiles {
  attachedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  fileId: string;
  noteId: string;
}

export interface AppNotes {
  archivedAt: ColumnType<string, Date | string, Date | string> | null;
  content: Generated<string>;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  currentVersionId: string | null;
  excerpt: string | null;
  id: Generated<string>;
  isLocked: Generated<boolean>;
  ownerUserid: string;
  parentNoteId: string | null;
  source: string | null;
  title: string | null;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppPlaidItems {
  accessToken: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  cursor: string | null;
  errorCode: string | null;
  errorMessage: string | null;
  id: Generated<string>;
  institutionId: string | null;
  lastSyncedAt: ColumnType<string, Date | string, Date | string> | null;
  provider: Generated<string>;
  providerItemId: string;
  status: Generated<string>;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface AppTagAssignments {
  assignedByUserid: string | null;
  assignmentPeriod: Generated<string | null>;
  assignmentSource: Generated<string>;
  confidence: Numeric | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  entityId: string;
  entityTable: string;
  id: Generated<string>;
  removedAt: ColumnType<string, Date | string, Date | string> | null;
  tagId: string;
}

export interface AppTags {
  archivedAt: ColumnType<string, Date | string, Date | string> | null;
  color: string | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  createdByUserid: string | null;
  description: string | null;
  icon: string | null;
  id: Generated<string>;
  name: string;
  ownerUserid: string;
  path: string;
  slug: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppTaskParticipants {
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  displayName: string;
  email: string | null;
  id: Generated<string>;
  personId: string | null;
  taskId: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppTasks {
  completedAt: ColumnType<string, Date | string, Date | string> | null;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  description: string | null;
  dueAt: ColumnType<string, Date | string, Date | string> | null;
  durationMinutes: number | null;
  id: Generated<string>;
  location: string | null;
  ownerUserid: string;
  parentTaskId: string | null;
  primarySpaceId: string | null;
  priority: Generated<string>;
  scheduledEndAt: ColumnType<string, Date | string, Date | string> | null;
  scheduledStartAt: ColumnType<string, Date | string, Date | string> | null;
  schedulingWindowEndAt: ColumnType<string, Date | string, Date | string> | null;
  schedulingWindowStartAt: ColumnType<string, Date | string, Date | string> | null;
  status: Generated<string>;
  timeZone: string | null;
  title: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface AppVectorDocuments {
  content: string;
  createdat: Generated<ColumnType<string, Date | string, Date | string>>;
  embedding: string;
  entityId: string;
  entityType: string;
  id: Generated<string>;
  metadata: Json | null;
  ownerUserid: string;
  updatedat: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface DeviceCode {
  clientId: string | null;
  deviceCode: string;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  lastPolledAt: ColumnType<string, Date | string, Date | string> | null;
  pollingInterval: number | null;
  scope: string | null;
  status: string;
  userCode: string;
  userId: string | null;
}

export interface GooseDbVersion {
  id: Generated<number>;
  isApplied: boolean;
  tstamp: Generated<ColumnType<string, Date | string, Date | string>>;
  versionId: Int8;
}

export interface Jwks {
  createdAt: ColumnType<string, Date | string, Date | string>;
  expiresAt: ColumnType<string, Date | string, Date | string> | null;
  id: string;
  privateKey: string;
  publicKey: string;
}

export interface OauthAccessToken {
  accessToken: string;
  accessTokenExpiresAt: ColumnType<string, Date | string, Date | string>;
  clientId: string;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  refreshToken: string;
  refreshTokenExpiresAt: ColumnType<string, Date | string, Date | string>;
  scopes: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string | null;
}

export interface OauthApplication {
  clientId: string;
  clientSecret: string | null;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  disabled: Generated<boolean>;
  icon: string | null;
  id: string;
  metadata: string | null;
  name: string;
  redirectUrls: string;
  type: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string | null;
}

export interface OauthConsent {
  clientId: string;
  consentGiven: Generated<boolean>;
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  id: string;
  scopes: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userId: string;
}

export interface Passkey {
  aaguid: string | null;
  backedUp: Generated<boolean>;
  counter: Generated<number>;
  createdAt: ColumnType<string, Date | string, Date | string> | null;
  credentialID: string;
  deviceType: string;
  id: string;
  name: string | null;
  publicKey: string;
  transports: string | null;
  userId: string;
}

export interface Session {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<ColumnType<string, Date | string, Date | string>>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<ColumnType<string, Date | string, Date | string>>;
}

export interface Verification {
  createdAt: ColumnType<string, Date | string, Date | string> | null;
  expiresAt: ColumnType<string, Date | string, Date | string>;
  id: string;
  identifier: string;
  updatedAt: ColumnType<string, Date | string, Date | string> | null;
  value: string;
}

export interface DB {
  account: Account;
  'app.aiUsageEvents': AppAiUsageEvents;
  'app.careerApplicationFiles': AppCareerApplicationFiles;
  'app.careerApplicationNotes': AppCareerApplicationNotes;
  'app.careerApplications': AppCareerApplications;
  'app.careerApplicationStages': AppCareerApplicationStages;
  'app.careerCertifications': AppCareerCertifications;
  'app.careerEducation': AppCareerEducation;
  'app.careerOffers': AppCareerOffers;
  'app.careerPositions': AppCareerPositions;
  'app.careerProfile': AppCareerProfile;
  'app.careerProjects': AppCareerProjects;
  'app.careerSkills': AppCareerSkills;
  'app.careerSocialLinks': AppCareerSocialLinks;
  'app.careerTestimonials': AppCareerTestimonials;
  'app.chatMessages': AppChatMessages;
  'app.chats': AppChats;
  'app.files': AppFiles;
  'app.financeAccountLabels': AppFinanceAccountLabels;
  'app.financeAccounts': AppFinanceAccounts;
  'app.financeCategories': AppFinanceCategories;
  'app.financeInstitutions': AppFinanceInstitutions;
  'app.financeStatementPeriods': AppFinanceStatementPeriods;
  'app.financeTaxFilings': AppFinanceTaxFilings;
  'app.financeTaxFilingStatusEvents': AppFinanceTaxFilingStatusEvents;
  'app.financeTransactions': AppFinanceTransactions;
  'app.noteFiles': AppNoteFiles;
  'app.notes': AppNotes;
  'app.plaidItems': AppPlaidItems;
  'app.tagAssignments': AppTagAssignments;
  'app.tags': AppTags;
  'app.taskParticipants': AppTaskParticipants;
  'app.tasks': AppTasks;
  'app.vectorDocuments': AppVectorDocuments;
  deviceCode: DeviceCode;
  gooseDbVersion: GooseDbVersion;
  jwks: Jwks;
  oauthAccessToken: OauthAccessToken;
  oauthApplication: OauthApplication;
  oauthConsent: OauthConsent;
  passkey: Passkey;
  session: Session;
  user: User;
  verification: Verification;
}
