export enum JobApplicationStatus {
  APPLIED = 'APPLIED',
  PHONE_SCREEN = 'PHONE_SCREEN',
  INTERVIEW = 'INTERVIEW',
  FINAL_INTERVIEW = 'FINAL_INTERVIEW',
  OFFER = 'OFFER',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export const JOB_APPLICATION_STATUSES = Object.values(JobApplicationStatus);

export function isJobApplicationStatus(value: string): value is JobApplicationStatus {
  return JOB_APPLICATION_STATUSES.includes(value as JobApplicationStatus);
}

export enum JobApplicationStage {
  APPLICATION = 'APPLICATION',
  PHONE_SCREEN = 'PHONE_SCREEN',
  FIRST_INTERVIEW = 'FIRST_INTERVIEW',
  SECOND_INTERVIEW = 'SECOND_INTERVIEW',
  FINAL_INTERVIEW = 'FINAL_INTERVIEW',
  TECHNICAL_INTERVIEW = 'TECHNICAL_INTERVIEW',
  OFFER = 'OFFER',
  BACKGROUND_CHECK = 'BACKGROUND_CHECK',
  REFERENCE_CHECK = 'REFERENCE_CHECK',
}
