import { type RouteConfig, index, layout, route } from '@react-router/dev/routes';

export default [
  index('routes/home.tsx'),
  route('/auth', 'routes/auth/index.tsx'),
  route('/login', 'routes/login.tsx'),
  route('/demo', 'routes/demo.tsx'),
  route('prototypes/application-cockpit', 'routes/prototypes.application-cockpit.tsx'),
  route('health', 'routes/health.ts'),
  route('api/portfolio/:owner_userid', 'routes/api.portfolio.$userId.ts'),
  route('api/career/applications', 'routes/api.career.applications.ts'),
  // Used only by the onboarding "create my first profile" flow (UploadResumeForm mode="create").
  route('api/resume/convert', 'routes/api.resume.convert.ts'),
  route('api/resume/analyze', 'routes/api.resume.analyze.ts'),
  route('api/resume/jobs/:jobId/stream', 'routes/api.resume.jobs.$jobId.stream.ts'),
  route('api/resume/customize', 'routes/api.resume.customize.ts'),
  route('api/skills/derive', 'routes/api.skills.derive.ts'),
  route('api/skills/search', 'routes/api.skills.search.ts'),
  route('api/validate-slug', 'routes/api.validate-slug.ts'),
  route('api/job/scrape', 'routes/api.job.scrape.ts'),
  route('api/job/import', 'routes/api.job.import.ts'),
  route('p/:slug', 'routes/p.$slug.tsx'),
  layout('routes/_authenticated.tsx', [
    route('onboarding', 'routes/onboarding.tsx'),
    layout('routes/_authenticated-pages.tsx', [
      route('account', 'routes/account.tsx'),
      route('profile', 'routes/profile.tsx'),
      layout('routes/_profile-required.tsx', [
        route('work', 'routes/work.tsx'),
        route('work/new', 'routes/work.new.tsx'),
        route('work/:id', 'routes/work.$id.tsx'),
        route('skills', 'routes/skills.tsx'),
        route('projects', 'routes/projects.tsx'),
        route('projects/new', 'routes/projects.new.tsx'),
        route('projects/:id', 'routes/projects.$id.tsx'),
        route('testimonials', 'routes/testimonials.tsx'),
        route('testimonials/new', 'routes/testimonials.new.tsx'),
        route('testimonials/:id', 'routes/testimonials.$id.tsx'),
        route('applications', 'routes/applications.tsx'),
        route('applications/new', 'routes/applications.new.tsx'),
        route('applications/:id', 'routes/applications.$id.tsx', [
          index('routes/applications.$id._index.tsx'),
          route('timeline', 'routes/applications.$id.timeline.tsx'),
          route('notes', 'routes/applications.$id.notes.tsx'),
          route('files', 'routes/applications.$id.files.tsx'),
          route('resume', 'routes/applications.$id.resume.tsx'),
        ]),
      ]),
    ]),
    route('*', 'routes/not-found.tsx'),
  ]),
] satisfies RouteConfig;
