import { pgTable, index, foreignKey, unique, pgPolicy, text, uuid, timestamp, check, integer, varchar, uniqueIndex, jsonb, boolean, numeric, date, bigint, primaryKey, pgView, interval, vector, geometry } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

/**
 * bookmarks domain schema slice
 * 
 * Generated by scripts/generate-db-schema-slices.ts
 * Do not edit manually.
 * 
 * Tables in this domain:
 *   - bookmarks
 */

export const bookmarks = pgTable("bookmarks", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull(),
	url: text().notNull(),
	title: text(),
	description: text(),
	favicon: text(),
	thumbnail: text(),
	source: text(),
	folder: text(),
	data: jsonb().default({}),
	// TODO: failed to parse database type 'tsvector'
	searchVector: text("search_vector").generatedAlwaysAs(sql`to_tsvector('english'::regconfig, ((((COALESCE(title, ''::text) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(url, ''::text)))`),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("bookmarks_folder_idx").using("btree", table.userId.asc().nullsLast().op("text_ops"), table.folder.asc().nullsLast().op("text_ops")).where(sql`(folder IS NOT NULL)`),
	index("bookmarks_search_idx").using("gin", table.searchVector.asc().nullsLast().op("tsvector_ops")),
	index("bookmarks_user_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "bookmarks_user_id_fkey"
		}).onDelete("cascade"),
	unique("bookmarks_user_id_url_key").on(table.url, table.userId),
	pgPolicy("bookmarks_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`  }),
]);
