import { pgTable, index, foreignKey, unique, pgPolicy, text, uuid, timestamp, check, integer, varchar, uniqueIndex, jsonb, boolean, numeric, date, bigint, primaryKey, pgView, interval, vector, geometry } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

/**
 * finance domain schema slice
 * 
 * Generated by scripts/generate-db-schema-slices.ts
 * Do not edit manually.
 * 
 * Tables in this domain:
 *   - financeAccounts
 *   - financeCategories
 *   - financeTransactions2022
 *   - financeTransactions2023
 *   - financeTransactions2024
 *   - financeTransactions2025
 *   - financeTransactions2026
 *   - financeTransactionsDefault
 */

export const financeAccounts = pgTable("finance_accounts", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull(),
	name: text().notNull(),
	accountType: text("account_type").notNull(),
	institutionName: text("institution_name"),
	institutionId: text("institution_id"),
	balance: numeric({ precision: 12, scale:  2 }).default('0'),
	currency: text().default('USD'),
	isActive: boolean("is_active").default(true),
	data: jsonb().default({}),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("finance_accounts_active_idx").using("btree", table.userId.asc().nullsLast().op("text_ops"), table.accountType.asc().nullsLast().op("text_ops")).where(sql`(is_active = true)`),
	index("finance_accounts_user_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "finance_accounts_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("finance_accounts_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`  }),
]);

export const financeCategories = pgTable("finance_categories", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull(),
	name: text().notNull(),
	parentId: uuid("parent_id"),
	icon: text(),
	color: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("finance_categories_parent_idx").using("btree", table.parentId.asc().nullsLast().op("uuid_ops")),
	index("finance_categories_user_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.parentId],
			foreignColumns: [table.id],
			name: "finance_categories_parent_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "finance_categories_user_id_fkey"
		}).onDelete("cascade"),
	unique("finance_categories_user_id_name_key").on(table.name, table.userId),
	pgPolicy("finance_categories_tenant_policy", { as: "permissive", for: "all", to: ["public"], using: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`, withCheck: sql`(app_is_service_role() OR (user_id = app_current_user_id()))`  }),
]);

export const financeTransactions2022 = pgTable("finance_transactions_2022", {
	id: uuid().defaultRandom().notNull(),
	userId: uuid("user_id").notNull(),
	accountId: uuid("account_id").notNull(),
	amount: numeric({ precision: 12, scale:  2 }).notNull(),
	transactionType: text("transaction_type").notNull(),
	categoryId: uuid("category_id"),
	category: text(),
	description: text(),
	merchantName: text("merchant_name"),
	date: date().notNull(),
	dateRaw: text("date_raw"),
	pending: boolean().default(false),
	source: text(),
	externalId: text("external_id"),
	data: jsonb().default({}),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("finance_transactions_2022_account_id_date_idx").using("btree", table.accountId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("uuid_ops")),
	index("finance_transactions_2022_date_idx").using("brin", table.date.asc().nullsLast().op("date_minmax_ops")).with({pages_per_range: "32"}),
	index("finance_transactions_2022_user_id_category_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.categoryId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")).where(sql`(category_id IS NOT NULL)`),
	index("finance_transactions_2022_user_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")),
	index("finance_transactions_2022_user_id_date_idx1").using("btree", table.userId.asc().nullsLast().op("date_ops"), table.date.desc().nullsFirst().op("uuid_ops")).where(sql`(pending = true)`),
	primaryKey({ columns: [table.date, table.id], name: "finance_transactions_2022_pkey"}),
]);

export const financeTransactions2023 = pgTable("finance_transactions_2023", {
	id: uuid().defaultRandom().notNull(),
	userId: uuid("user_id").notNull(),
	accountId: uuid("account_id").notNull(),
	amount: numeric({ precision: 12, scale:  2 }).notNull(),
	transactionType: text("transaction_type").notNull(),
	categoryId: uuid("category_id"),
	category: text(),
	description: text(),
	merchantName: text("merchant_name"),
	date: date().notNull(),
	dateRaw: text("date_raw"),
	pending: boolean().default(false),
	source: text(),
	externalId: text("external_id"),
	data: jsonb().default({}),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("finance_transactions_2023_account_id_date_idx").using("btree", table.accountId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("uuid_ops")),
	index("finance_transactions_2023_date_idx").using("brin", table.date.asc().nullsLast().op("date_minmax_ops")).with({pages_per_range: "32"}),
	index("finance_transactions_2023_user_id_category_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.categoryId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")).where(sql`(category_id IS NOT NULL)`),
	index("finance_transactions_2023_user_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")),
	index("finance_transactions_2023_user_id_date_idx1").using("btree", table.userId.asc().nullsLast().op("date_ops"), table.date.desc().nullsFirst().op("uuid_ops")).where(sql`(pending = true)`),
	primaryKey({ columns: [table.date, table.id], name: "finance_transactions_2023_pkey"}),
]);

export const financeTransactions2024 = pgTable("finance_transactions_2024", {
	id: uuid().defaultRandom().notNull(),
	userId: uuid("user_id").notNull(),
	accountId: uuid("account_id").notNull(),
	amount: numeric({ precision: 12, scale:  2 }).notNull(),
	transactionType: text("transaction_type").notNull(),
	categoryId: uuid("category_id"),
	category: text(),
	description: text(),
	merchantName: text("merchant_name"),
	date: date().notNull(),
	dateRaw: text("date_raw"),
	pending: boolean().default(false),
	source: text(),
	externalId: text("external_id"),
	data: jsonb().default({}),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("finance_transactions_2024_account_id_date_idx").using("btree", table.accountId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("uuid_ops")),
	index("finance_transactions_2024_date_idx").using("brin", table.date.asc().nullsLast().op("date_minmax_ops")).with({pages_per_range: "32"}),
	index("finance_transactions_2024_user_id_category_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.categoryId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")).where(sql`(category_id IS NOT NULL)`),
	index("finance_transactions_2024_user_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")),
	index("finance_transactions_2024_user_id_date_idx1").using("btree", table.userId.asc().nullsLast().op("date_ops"), table.date.desc().nullsFirst().op("uuid_ops")).where(sql`(pending = true)`),
	primaryKey({ columns: [table.date, table.id], name: "finance_transactions_2024_pkey"}),
]);

export const financeTransactions2025 = pgTable("finance_transactions_2025", {
	id: uuid().defaultRandom().notNull(),
	userId: uuid("user_id").notNull(),
	accountId: uuid("account_id").notNull(),
	amount: numeric({ precision: 12, scale:  2 }).notNull(),
	transactionType: text("transaction_type").notNull(),
	categoryId: uuid("category_id"),
	category: text(),
	description: text(),
	merchantName: text("merchant_name"),
	date: date().notNull(),
	dateRaw: text("date_raw"),
	pending: boolean().default(false),
	source: text(),
	externalId: text("external_id"),
	data: jsonb().default({}),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("finance_transactions_2025_account_id_date_idx").using("btree", table.accountId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("uuid_ops")),
	index("finance_transactions_2025_date_idx").using("brin", table.date.asc().nullsLast().op("date_minmax_ops")).with({pages_per_range: "32"}),
	index("finance_transactions_2025_user_id_category_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.categoryId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")).where(sql`(category_id IS NOT NULL)`),
	index("finance_transactions_2025_user_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")),
	index("finance_transactions_2025_user_id_date_idx1").using("btree", table.userId.asc().nullsLast().op("date_ops"), table.date.desc().nullsFirst().op("uuid_ops")).where(sql`(pending = true)`),
	primaryKey({ columns: [table.date, table.id], name: "finance_transactions_2025_pkey"}),
]);

export const financeTransactions2026 = pgTable("finance_transactions_2026", {
	id: uuid().defaultRandom().notNull(),
	userId: uuid("user_id").notNull(),
	accountId: uuid("account_id").notNull(),
	amount: numeric({ precision: 12, scale:  2 }).notNull(),
	transactionType: text("transaction_type").notNull(),
	categoryId: uuid("category_id"),
	category: text(),
	description: text(),
	merchantName: text("merchant_name"),
	date: date().notNull(),
	dateRaw: text("date_raw"),
	pending: boolean().default(false),
	source: text(),
	externalId: text("external_id"),
	data: jsonb().default({}),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("finance_transactions_2026_account_id_date_idx").using("btree", table.accountId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("uuid_ops")),
	index("finance_transactions_2026_date_idx").using("brin", table.date.asc().nullsLast().op("date_minmax_ops")).with({pages_per_range: "32"}),
	index("finance_transactions_2026_user_id_category_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.categoryId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")).where(sql`(category_id IS NOT NULL)`),
	index("finance_transactions_2026_user_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")),
	index("finance_transactions_2026_user_id_date_idx1").using("btree", table.userId.asc().nullsLast().op("date_ops"), table.date.desc().nullsFirst().op("uuid_ops")).where(sql`(pending = true)`),
	primaryKey({ columns: [table.date, table.id], name: "finance_transactions_2026_pkey"}),
]);

export const financeTransactionsDefault = pgTable("finance_transactions_default", {
	id: uuid().defaultRandom().notNull(),
	userId: uuid("user_id").notNull(),
	accountId: uuid("account_id").notNull(),
	amount: numeric({ precision: 12, scale:  2 }).notNull(),
	transactionType: text("transaction_type").notNull(),
	categoryId: uuid("category_id"),
	category: text(),
	description: text(),
	merchantName: text("merchant_name"),
	date: date().notNull(),
	dateRaw: text("date_raw"),
	pending: boolean().default(false),
	source: text(),
	externalId: text("external_id"),
	data: jsonb().default({}),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("finance_transactions_default_account_id_date_idx").using("btree", table.accountId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("uuid_ops")),
	index("finance_transactions_default_date_idx").using("brin", table.date.asc().nullsLast().op("date_minmax_ops")).with({pages_per_range: "32"}),
	index("finance_transactions_default_user_id_category_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.categoryId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")).where(sql`(category_id IS NOT NULL)`),
	index("finance_transactions_default_user_id_date_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops"), table.date.desc().nullsFirst().op("date_ops")),
	index("finance_transactions_default_user_id_date_idx1").using("btree", table.userId.asc().nullsLast().op("date_ops"), table.date.desc().nullsFirst().op("uuid_ops")).where(sql`(pending = true)`),
	primaryKey({ columns: [table.date, table.id], name: "finance_transactions_default_pkey"}),
]);
