[core]
	engine = pg
	plan_file = sqitch.plan
	top_dir = .

[engine "pg"]
	registry = sqitch

[target "dev"]
	uri = db:pg://postgres:postgres@localhost:5434/hominem

[target "test"]
	uri = db:pg://postgres:postgres@localhost:4433/hominem-test
