name: create-release

on:
  workflow_run:
    workflows: ["deploy-api-prod"]
    branches: [main]
    # Required to run only on successful completion of the code-quality workflow
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: release-please-action
        uses: googleapis/release-please-action@v4.2.0
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
