name: deploy-api-prod

on:
  workflow_run:
    workflows: ["docker-publish-api"]
    branches: [main]
    types:
      - completed

jobs:
  call-reusable-deploy:
    name: Deploy API to Railway
    # Only run if the triggering workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable-deploy-railway.yml
    with:
      service-id: ${{ secrets.RAILWAY_SERVICE_API }}
    secrets:
      railway-token: ${{ secrets.RAILWAY_TOKEN }}
