name: deploy-api-prod

on:
  workflow_run:
    workflows: ["docker-publish-api"]
    branches: [main]
    # Required to run only on successful completion of the code-quality workflow
    types:
      - completed
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_API }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.workflow_id != github.workflow }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v4
      - name: Deploy
        run: railway up --service ${{ env.SERVICE_ID }}
