name: web-deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["code-quality"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_WEB }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v4
      - name: Deploy
        run: railway up --service ${{ env.SERVICE_ID }} --detach
