name: deploy-worker-transactions-import

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'apps/workers/**'
      - 'packages/utils/**'
      - '.github/workflows/deploy-worker-transactions-import.yml'

jobs:
  deploy:
    name: Deploy Workers to Railway
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_IMPORT_TRANSACTIONS }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1 # Use a more recent version
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Railway
        run: railway up --service ${{ env.SERVICE_ID }} --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
