name: deploy-api-prod

on:
  workflow_run:
    workflows: ["deploy-db"]
    branches: [main]
    # Required to run only on successful completion of the code-quality workflow
    types:
      - completed
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.workflow_id != github.workflow }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: 📦 Install dependencies
        run: bun install

      - name: Install Railway
        run: bun install --global @railway/cli
        
      - name: Deploy
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_API }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
