name: deploy-api-prod

on:
  workflow_run:
    workflows: ["docker-publish-api"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy API to Railway
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable-deploy-railway.yml
    with:
      service-id: ${{ secrets.RAILWAY_SERVICE_API }}
