name: web-deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - "packages/**"
      - ".github/workflows/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_WEB }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v4
      - name: Deploy
        run: railway up --service ${{ env.SERVICE_ID }} --detach
