name: deploy-workers-prod

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'apps/workers/**'
      - 'packages/utils/**'
      - '.github/workflows/deploy-workers-prod.yml'

jobs:     
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_IMPORT_TRANSACTIONS }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v4
      - name: Deploy to Railway
        run: railway up --service ${{ env.SERVICE_ID }} --detach
