name: deploy-workers

on:
  workflow_dispatch: # Allow manual trigger
  workflow_run:
    workflows: ['code-quality']
    branches: [main]
    types:
      - completed

concurrency:
  group: deploy-workers-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Workers to Fly
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Workers to Fly
        run: flyctl deploy --config infra/fly/apps/workers.toml --app hominem-workers --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
