name: web-deploy

on:
  workflow_dispatch: # Allow manual trigger
  workflow_run:
    workflows: ["code-quality"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Web to Railway
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_WEB }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1 # Use a more recent version
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Railway
        run: railway up --service ${{ env.SERVICE_ID }} --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
