name: deploy-rocco-prod

on:
  workflow_run:
    workflows: ["code-quality"]
    branches: [main]
    types:
      - completed
  
jobs:
  deploy:
    name: Deploy Rocco to Railway
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container: ghcr.io/railwayapp/cli:latest
    env:
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ROCCO }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@v4
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Railway
        run: railway up --service ${{ env.SERVICE_ID }} --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
