name: docker-publish-api

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        env:
          APP_URL: ${{ secrets.APP_URL }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          COOKIE_DOMAIN: ${{ secrets.COOKIE_DOMAIN }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
          COOKIE_SALT: ${{ secrets.COOKIE_SALT }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NODE_ENV: production
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        with:
          context: .
          file: ./docker/api.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_URL: ${{ secrets.APP_URL }}
            CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
            COOKIE_DOMAIN: ${{ secrets.COOKIE_DOMAIN }}
            COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
            COOKIE_SALT: ${{ secrets.COOKIE_SALT }}
            COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
            NODE_ENV: production
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            REDIS_URL: ${{ secrets.REDIS_URL }}
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
