name: Reusable Railway Deploy

on:
  workflow_call:
    inputs:
      service-id:
        description: 'The Railway service ID to deploy to'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    environment: production # Optional: Define environment if needed
    concurrency:
      group: railway-deploy-${{ inputs.service-id }}
      cancel-in-progress: true
    env:
      RAILWAY_TOKEN: ${{ secrets.railway-token }}
      SERVICE_ID: ${{ inputs.service-id }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1 # Use a more recent version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        run: railway up --service ${{ env.SERVICE_ID }} --detach
